version: '3'

services:
    app:
        build:
            context: .
            dockerfile: ./etc/app/Dockerfile
        env_file:
            - ./etc/app/.env
            - ./etc/db/.env
        depends_on:
            - db
        networks:
            - remindme
        ports:
            - 10000:8000
        volumes:
            - ./src/remindme_app:/app/remindme_app
            - ./etc/app/pyproject.toml:/app/pyproject.toml
            - ./etc/app/poetry.lock:/app/poetry.lock

    db:
        image: postgres:10
        restart: 'no'
        env_file: ./etc/db/.env
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - 10432:5432
        networks:
            - remindme

    rabbitmq:
        image: rabbitmq:alpine
        env_file: ./etc/rabbitmq/.env
        ports:
            - "10672:5672"
        networks:
            - remindme

volumes:
    postgres: {}

networks:
    remindme:
        external:
            name: remindme