# Generated by Django 3.1.1 on 2020-09-06 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remindme_api', '0002_auto_20200904_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(unique=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remindme_api.reminder')),
            ],
        ),
    ]
