# Generated by Django 3.1.1 on 2020-09-06 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remindme_api', '0003_remindertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindertask',
            name='reminder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='remindme_api.reminder'),
        ),
    ]
